### ISSUE TITLE
Allow wildcards in except URLs array

### ISSUE THREAD

**Issue by dvlpp** [code16/privat#1]
As discussed here: https://github.com/dvlpp/privat/issues/4.

**Comment by AlexECP** [comment]
Maybe im misunderstanding something, but instead of registering under middlewareGroups, register under routeMiddleware, then you can just apply the middleware to specific routes or route groups, and any route without it is excluded.

**Comment by dvlpp** [comment]
@AlexECP you are right. I'm closing this (thought it already was the case).
